"""new fields in user model

Revision ID: 65007f6cea87
Revises: 4e04d34448cf
Create Date: 2020-04-02 08:47:05.438845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65007f6cea87'
down_revision = '4e04d34448cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
